### ISSUE TITLE
Sort/unsort on PropertyTable

### ISSUE THREAD

**Issue by morgsie** [lcaron/opal#74]
Hi Laurent,
We have come across an issue, which I hope you will be able to help us with. Towards the end of last year you fixed an issue on the unsort() routine for the PropertyTable. I have applied your new opal-1.0.8, thank you!
We had understood that by using the unsort() option the properties would be displayed in the order of the getPropertiesAsList() and not sorted alphabetically by Category.  However, this does not seem to be the case?

Please see an example of our code attached along with the output and the final table, which is displayed. There seems to be no reason to the order they are being displayed? We would appreciate if you could help us understand this so that we can display the properties in the order we want.

Thank you in anticipation.
Kind Regards,
Mhorag Lane
[example of code.txt](https://github.com/lcaron/opal/files/1618704/example.of.code.txt)
![propertytable](https://user-images.githubusercontent.com/34470075/34772861-7697b6aa-f601-11e7-9c35-f895b44373c7.JPG)
[output.txt](https://github.com/lcaron/opal/files/1618705/output.txt)

**Comment by lcaron** [comment]
Fixed in release V1.0.9

**Comment by morgsie** [comment]
Hi Laurent,
Thank you so much for looking at this issue for me. I have just applied opal 1.0.9 and unfortunately the issue you fixed for me in a previous release for the nullpointerexception in the unsort() routine seems to have crept back in:

java.lang.NullPointerException
	at org.mihalis.opal.propertyTable.PTWidgetTree.refillData(PTWidgetTree.java:186)
	at org.mihalis.opal.propertyTable.PropertyTable.unsort(PropertyTable.java:263)

When I revert to 1.0.8 I don't get the null pointer exception on unsort(), but I then obviously still have the issue that the properties don't display in the order in which I add them to the table.
I am trying to find the opal project or the PropertyTable on the Nebula site, but don't seem to be having much luck. Hoping you will see this in the meantime.

Kind Regards,
Mhorag

**Comment by morgsie** [comment]
Hi Laurent,
Thank you so much for looking at this issue for me. I have just applied opal 1.0.9 and unfortunately the issue you fixed for me in a previous release for the nullpointerexception in the unsort() routine seems to have crept back in:
java.lang.NullPointerException
at org.mihalis.opal.propertyTable.PTWidgetTree.refillData(PTWidgetTree.java:186)
at org.mihalis.opal.propertyTable.PropertyTable.unsort(PropertyTable.java:263)
When I revert to 1.0.8 I don't get the null pointer exception on unsort(), but I then obviously still have the issue that the properties don't display in the order in which I add them to the table.
I am trying to find the opal project or the PropertyTable on the Nebula site, but don't seem to be having much luck. Hoping you will see this in the meantime.
Kind Regards,
Mhorag

**Comment by lcaron** [comment]
Hi Mhorag 

I've updated the class. Please download again V1.0.9 and keep me informed.

Laurent

**Comment by morgsie** [comment]
Hi Laurent,
Thank you - I am no longer getting the nullpointer exception. 
However, when I have the table unsorted I am still seeing the properties in random order. They are not appearing in the order in which I would have hoped (which is the order in which I have input them).
Perhaps I am misunderstanding the unsort()?
I had thought they would display in the order in which they display when I see them in when I look at the properties ArrayList<E> during debug. They are in the Arraylist in the same order in which I input them. However, when they display they are in a random order.
Thanks,
Mhorag

**Comment by lcaron** [comment]
OMG I think I just understood the problem... Please try with the latest version I uploaded a few minutes ago. Thank you for your feedback.

**Comment by morgsie** [comment]
Hi Laurent,
Thank you - I am no longer getting the nullpointer exception. 
However, when I have the table unsorted I am still seeing the properties in random order. They are not appearing in the order in which I would have hoped (which is the order in which I have input them).
Perhaps I am misunderstanding the unsort()?
I had thought they would display in the order in which they display when I see them in when I look at the properties ArrayList<E> during debug. They are in the Arraylist in the same order in which I input them. However, when they display they are in a random order.
Thanks,
Mhorag

**Comment by morgsie** [comment]
Hi Laurent,
Thank you for the latest version - unfortunately I am still not seeing what I would expect. I have put it into this document so that hopefully you can understand my problem.
Thank you so much for your time and efforts!
Mhorag
[opal PropTable issue.docx](https://github.com/lcaron/opal/files/1715965/opal.PropTable.issue.docx)

**Comment by lcaron** [comment]
Hi Morag,

Well, the bug was fixed but I dropped the wrong file. Please download the very last release, it should be ok.
Please give me your feedback.

**Comment by morgsie** [comment]
Thanks so much Laurent, that is perfect :-)
Mhorag

**Comment by lcaron** [comment]
Great news ! Happy to help...
